#ifndef _KEYBINDS_H
#define _KEYBINDS_H

#define KEYBIND_TABLE_UP 'k'
#define KEYBIND_TABLE_DOWN 'j'
#define KEYBIND_TABLE_LEFT 'h'
#define KEYBIND_TABLE_RIGHT 'l'
#define KEYBIND_TABLE_REPLACE 'r'
#define KEYBIND_TABLE_NEXT 't'
#define KEYBIND_TABLE_NEW 'n'
#define KEYBIND_TABLE_INCREMENT '+'
#define KEYBIND_TABLE_DECREMENT '-'
///
#define KEYBIND_ROTATE_LEFT 'h'
#define KEYBIND_ROTATE_RIGHT 'l'
#define KEYBIND_ROTATE_UP 'k'
#define KEYBIND_ROTATE_DOWN 'j'
//
#define KEYBIND_TRANSLATE_LEFT 'h'
#define KEYBIND_TRANSLATE_RIGHT 'l'
#define KEYBIND_TRANSLATE_UP 'k'
#define KEYBIND_TRANSLATE_DOWN 'j'
#define KEYBIND_ALL_SWITCH_MODE 'm'
//
#define KEYBIND_VISUAL_LEFT 'h'
#define KEYBIND_VISUAL_RIGHT 'l'
#define KEYBIND_VISUAL_UP 'k'
#define KEYBIND_VISUAL_DOWN 'j'
#define KEYBIND_VISUAL_FORWARD 'u'
#define KEYBIND_VISUAL_BACK 'i'
#define KEYBIND_VISUAL_NEXT_POINT 'p'
#define KEYBIND_VISUAL_NEW 'n'
#define KEYBIND_VISUAL_NEXT_TRIANGLE 't'
//
#endif
