#ifndef _GEOM_H
#define _GEOM_H
#define CUBE(WIDTH)\
			{-WIDTH,-WIDTH,-WIDTH*2},{WIDTH, -WIDTH, -WIDTH*2}, {WIDTH,WIDTH,-WIDTH*2}, \
			{-WIDTH,-WIDTH,-WIDTH*2}, {-WIDTH, WIDTH, -WIDTH*2}, {WIDTH,WIDTH,-WIDTH*2}, \
			{-WIDTH,-WIDTH,WIDTH*2}, {WIDTH, -WIDTH, WIDTH*2}, {WIDTH,WIDTH,WIDTH*2}, \
			{-WIDTH,-WIDTH,WIDTH*2}, {-WIDTH, WIDTH, WIDTH*2}, {WIDTH,WIDTH,WIDTH*2}, \
			{-WIDTH,-WIDTH,-WIDTH*2}, {-WIDTH, -WIDTH, WIDTH*2}, {-WIDTH,WIDTH,WIDTH*2}, \
			{-WIDTH,-WIDTH,-WIDTH*2}, {-WIDTH, WIDTH, -WIDTH*2}, {-WIDTH,WIDTH,WIDTH*2}, \
			{WIDTH,-WIDTH,-WIDTH*2}, {WIDTH, -WIDTH, WIDTH*2}, {WIDTH,WIDTH,WIDTH*2}, \
			{WIDTH,-WIDTH,-WIDTH*2}, {WIDTH, WIDTH, -WIDTH*2}, {WIDTH,WIDTH,WIDTH*2}, \
			{-WIDTH,WIDTH,-WIDTH*2}, {-WIDTH, WIDTH, WIDTH*2}, {WIDTH,WIDTH,WIDTH*2}, \
			{-WIDTH,WIDTH,-WIDTH*2}, {WIDTH, WIDTH, -WIDTH*2}, {WIDTH,WIDTH,WIDTH*2}, \
			{-WIDTH,-WIDTH,-WIDTH*2}, {-WIDTH, -WIDTH, WIDTH*2}, {WIDTH,-WIDTH,WIDTH*2}, \
			{-WIDTH,-WIDTH,-WIDTH*2}, {WIDTH, -WIDTH, -WIDTH*2}, {WIDTH,-WIDTH,WIDTH*2} 
//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAa
#define CUBE_VECTS  36
#define	CUBE_TRIS  12
#endif
